---

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: test-ag-aw-tester
    docker_networks:
      - name: 'test-ag-aw'
        ipam_config:
          - subnet: '192.168.17.0/24'
            gateway: '192.168.17.254'
    networks:
      - name: 'test-ag-aw'
        ipv4_address: '192.168.17.1'
    etc_hosts: {aw.test.oxl.at: '192.168.17.2'}
    groups: [grp_tester]
    docker_host: 'tcp://molecule-docker.local:2375'
    image: 'ansible0guy/molecule:debian-latest'
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

  - name: test-ag-aw-1
    networks:
      - name: 'test-ag-aw'
        ipv4_address: '192.168.17.2'
    groups: [grp_targets]
    docker_host: 'tcp://molecule-docker.local:2375'
    image: 'ansible0guy/molecule:debian-latest'
    tmpfs: ['/tmp', '/run', '/run/lock']
    privileged: true
    command: '/sbin/init'

provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: '/tmp'
      no_target_syslog: true
verifier:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify  # MUST NOT make changes
    - idempotence
    - check
    - destroy
