---

- name: Verify
  hosts: grp_tester
  gather_facts: false
  tasks:
    - name: Checking if web-service is reachable
      ansible.builtin.uri:
        url: 'https://aw.test.ansibleguy.net'
        return_content: yes
        validate_certs: false
      register: page
      failed_when: "'Ansible WebUI' not in page.content"
