---

- name: Ansible-WebUI | Backup | Service & Timer
  ansible.builtin.template:
    src: "templates/etc/systemd/system/ansible-webui-backup.{{ item }}.j2"
    dest: "/etc/systemd/system/ansible-webui-backup.{{ item }}"
    mode: 0644
  loop: ['service', 'timer']

- name: Ansible-WebUI | Backup | Enabling Backup
  ansible.builtin.systemd:
    name: 'ansible-webui-backup.timer'
    enabled: true
    state: started
    daemon_reload: true
