---

- name: Ansible-WebUI | Webserver | Allow to read static-files
  ansible.builtin.user:
    name: 'www-data'
    append: true
    groups: "{{ AW_HC.user }}"

- name: Ansible-WebUI | Resolve statics-path
  ansible.builtin.command: "ls {{ AW_CONFIG.path.venv }}/lib/"
  check_mode: false
  changed_when: false
  register: aw_venv_py_version

- name: Ansible-WebUI | Installing/Configuring nginx
  ansible.builtin.import_role:
    name: oxlorg.nginx
  when: AW_CONFIG.manage.webserver | bool
  vars:
    venv_base: "{{ AW_CONFIG.path.venv }}/lib/{{ aw_venv_py_version.stdout_lines[0] }}/site-packages"
    aw_nginx_config_overrides:
      domain: "{{ AW_CONFIG.config['AW_HOSTNAMES'] | ensure_list | first }}"
      aliases: "{{ [] if AW_CONFIG.config['AW_HOSTNAMES'] | ensure_list | length == 1 else AW_CONFIG.config['AW_HOSTNAMES'][1:] }}"
      config_additions:
        - 'location ~ ^/static/admin/ {'
        - '  root {{ venv_base }}/django/contrib/admin/;'
        - '  try_files $uri =404;'
        - '}'
        - 'location /static/dist/ {'
        - '  alias {{ venv_base }}/oxl_ansible_webui/aw/static_prod/dist/;'
        - '  try_files $uri =404;'
        - '}'
        - 'location /static/img/ {'
        - '  alias {{ venv_base }}/oxl_ansible_webui/aw/static/img;'
        - '  try_files $uri =404;'
        - '}'
        - 'location /static/css/ {'
        - '  alias {{ venv_base }}/oxl_ansible_webui/aw/static/css;'
        - '  try_files $uri =404;'
        - '}'
      proxy:
        port: "{{ AW_CONFIG.config.AW_PORT }}"

    nginx:
      sites:
        ansiblewebui: "{{ AW_CONFIG.nginx | combine(aw_nginx_config_overrides, recursive=true) }}"
